pipeline {
    agent any

    stages {
        stage('Switch to SSH') {
            steps {
                sshagent(credentials: ['jenkins-pod']) {
                    sh '''
                        git remote set-url origin git@github.com:anilthanki/jenkins-test.git
                        git fetch --all
                    '''
                }
            }
        }
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
